<?php

/**
 * Implements hook_block_info().
 */
function lth_submenu_block_info() {
  $blocks = array();

  $blocks['submenu'] = array(
    'info' => t('LTH Tabs Submenu'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'weight' => -100,
    'status' => 1,
    'region' => 'sidebar_first',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function lth_submenu_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'submenu':

      $submenu = menu_secondary_local_tasks();
      if (empty($submenu)) {
        break;
      }

      $menu = '<ul class="tabs--secondary nav-subtabs">'
                . render(menu_secondary_local_tasks())
              .'</ul>';

      $block = array(
        'title' => '<none>',
        'content' => $menu,
      );
      break;
  }

  return $block;
}

function lth_submenu_menu_tabs_primary($tabs) {

  if (count($tabs['#primary']) <= '1') return '';
  else return $tabs['#primary'];

}
